### ISSUE TITLE
深色模式下不兼容

### ISSUE THREAD

**Issue by bilirod** [zxhd863943427/siyuan-plugin-math-enhance#4]
![image](https://github.com/zxhd863943427/siyuan-plugin-math-enhance/assets/45555574/66096325-3cc9-4e8a-9128-c2aaaacd2856)

黑色背景下，下方显示公式的地方白色背景块挡住了白色字体

**Comment by zhoutaosheng** [comment]
深色主题不兼容+1

**Comment by mnyon** [comment]
我也出现了这个问题,非常影响编辑公式.
