### ISSUE TITLE
思源后台一直有两个报错

### ISSUE THREAD

**Issue by 5kyfkr** [zxhd863943427/siyuan-plugin-math-enhance#6]
![image](https://github.com/zxhd863943427/siyuan-plugin-math-enhance/assets/63196026/407be993-0675-4fe1-8bd3-a98b1263f961)
如上图，虽然不影响使用，但是每次调试的时候都会看到，还是希望能修一下

**Comment by zxhd863943427** [comment]
这两个报错的主要原因是依赖的库需要导入字体和声音文件，但思源不会读取这些内容，在插件上很难操作，只能直接修改库编译混淆后的js代码，或fork后进行修改。考虑到方便升级和不影响使用，所以没有处理这个报错。

**Comment by 5kyfkr** [comment]
> 这两个报错的主要原因是依赖的库需要导入字体和声音文件，但思源不会读取这些内容，在插件上很难操作，只能直接修改库编译混淆后的js代码，或fork后进行修改。考虑到方便升级和不影响使用，所以没有处理这个报错。

那以后也不会管了是吧，不管那我就关了这个issue了
